# Generated by Django 2.1.8 on 2019-05-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huayuan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='useremail',
            field=models.EmailField(max_length=20),
        ),
    ]
