# Generated by Django 2.1.8 on 2019-05-22 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huayuan', '0002_auto_20190522_1954'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register',
        ),
    ]
