# Generated by Django 2.1.8 on 2019-05-22 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huayuan', '0004_register'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='userRegister',
        ),
    ]
