# Generated by Django 2.1.8 on 2019-05-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huayuan', '0005_auto_20190522_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('useremail', models.EmailField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='reguster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u', models.CharField(max_length=20)),
                ('s', models.EmailField(max_length=20)),
                ('pa', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='userRegister',
        ),
    ]
