# Generated by Django 2.1.8 on 2019-05-22 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huayuan', '0007_auto_20190522_2104'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userRegister',
        ),
    ]
