# Generated by Django 2.1.8 on 2019-05-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huayuan', '0009_userregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='useremail',
            field=models.EmailField(max_length=254),
        ),
    ]
