# Generated by Django 2.1.8 on 2019-05-22 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huayuan', '0010_auto_20190522_2131'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
